version: '2'
services:    
  emulatorPlaystoreA8:
    environment:
        - DISPLAY
    privileged: true
    network_mode: "host"
    image: "d1alogo/android-emulator-x11:nexusPlaystoreA8"
    volumes:
        - "/usr/lib:/usr/lib"
        - "/tmp/.X11-unix:/tmp/.X11-unix"
        - "emudata:/opt/android-sdk-linux/.android"
        - "/etc/localtime:/etc/localtime"
        - "/etc/pulse"
        - "/run/user/${USER_GID}/pulse:/run/pulse:ro"
  emulatorA8:
    environment:
        - DISPLAY
    privileged: true
    network_mode: "host"
    image: "d1alogo/android-emulator-x11:nexusA8"
    volumes:
        - "/usr/lib:/usr/lib"
        - "/tmp/.X11-unix:/tmp/.X11-unix"
        - "emudata:/opt/android-sdk-linux/.android"
        - "/etc/localtime:/etc/localtime"
        - "/etc/pulse"
        - "/run/user/${USER_GID}/pulse:/run/pulse:ro"
  emulatorA7:
    environment:
        - DISPLAY
    privileged: true
    network_mode: "host"
    image: "d1alogo/android-emulator-x11:nexusA7"
    volumes:
        - "/usr/lib:/usr/lib"
        - "/tmp/.X11-unix:/tmp/.X11-unix"
        - "emudata:/opt/android-sdk-linux/.android"
        - "/etc/localtime:/etc/localtime"
        - "/etc/pulse"
        - "/run/user/${USER_GID}/pulse:/run/pulse:ro"
  development:
    privileged: true
    network_mode: "host"
    image: "d1alogo/android-react-native:sep17"
    volumes:
        - "/dev/bus/usb:/dev/bus/usb"
        - "devdata:/root"
        - "${HOME}:/userdata"
volumes:
    emudata:
    devdata:
